export default class{

    static btmanageProjects = '.row > .nav > :nth-child(3) > a'
    static btCreateNewProject = '.widget-toolbox > .form-inline > .btn'
    static txNameProject = '#project-name'
    static cbState = '#project-status'
    static slInheritGlobalCategories = '.lbl'
    static cbVisibilitie = '#project-view-state'
    static txDescription = '#project-description'
    static btAddProject = '.widget-toolbox > .btn'
    static messageValidationSucess = '.bold'
    static btProceed = '.alert > .btn-group > .btn'
    static txCreatedProject = 'tbody > tr > :nth-child(1) > a'
    static txCreatedSubProject = 'tbody > :nth-child(2) > :nth-child(1)'
    static btDeleteProject = '#project-delete-form > fieldset > .btn'
    static btConfirmDeleteProject = '.center > .btn'
    static btCreateSubproject = '#manage-project-update-subprojects-div > .widget-box > .widget-toolbox > .form-inline > .btn'
    static txValidationState = ':nth-child(2) > .category'
    static txNewCategory = '#project-add-category-form > fieldset > .input-sm'
    static btaddCategory = '[value="Adicionar Categoria"]'
    static textValidationCategory = '#categories > .widget-box > .widget-body > .widget-main > .table-responsive > .table > tbody > :nth-child(2) > :nth-child(1)'
    static btEditCategory = ':nth-child(1) > .form-inline > .btn'
    static txNameCategory = '#proj-category-name'
    static cbAssignTo = '#proj-category-assigned-to'
    static btUpdateCategory = '.widget-toolbox > .btn'
    static btDeleteCategory = 'div.inline > :nth-child(2) > .form-inline > .btn'
    static btConfirmDeleteCategory = '.center > .btn'
    static txNameVersion = '#manage-project-add-version-form > fieldset > .input-sm'
    static btAddVerion = '[name="add_version"]'
    static textValidationVersion = '#versions > tbody > tr > :nth-child(1)'
    static btEditVersion = ':nth-child(1) > .form-inline > .btn'
    static txNameEditVersion = '#proj-version-new-version'
    static txDataVersion = '#proj-version-date-order'
    static txDescriptionVersion = '#proj-version-description'
    static sbReleased = ':nth-child(4) > :nth-child(2) > label > .lbl'
    static btUpdateVersion = '.widget-toolbox > .btn'
    static btDeleteVersion = 'div.inline > :nth-child(2) > .form-inline > .btn'
    static btConfirmDeleteVersion = '.center > .btn'
}